app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# app/config/routing.yml

oc_platform:
    resource: "@OCPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

# On inclut également les routes de notre CoreBundle, sans préfixe
oc_core:
    resource: "@OCCoreBundle/Resources/config/routing.yml"

places:
    type: rest
    resource: AppBundle\Controller\PlaceController

prices:
    type:     rest
    resource: AppBundle\Controller\Place\PriceController

themes:
    type:     rest
    resource: AppBundle\Controller\Place\ThemeController

users:
    type: rest
    resource: AppBundle\Controller\UserController

preferences:
    type:     rest
    resource: AppBundle\Controller\User\PreferenceController

api_login_check:
    path: /s-api/login_check

#2login:
#2    path: /login
#2    defaults:
#2        _controller: OCUserBundle:Security:login

#2login_check:
#2    path: /login_check

#2logout:
#2    path: /logout

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
